### ISSUE TITLE
Dependency Problem with latest fsspec version

### ISSUE THREAD

**Issue by mfakaehler** [conda-forge/sshfs-feedstock#21]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm experiencing problems with importing the package, apperently due to issues with the latest fsspec version. This appreared for me of setting up a new env containing `dvc-ssh`, so @efiop, this might be relevant for the dvc-community. 

```python
>>> import sshfs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/maximilian/.conda/envs/test-sshfs/lib/python3.10/site-packages/sshfs/__init__.py", line 1, in <module>
    from sshfs.spec import SSHFileSystem
  File "/home/maximilian/.conda/envs/test-sshfs/lib/python3.10/site-packages/sshfs/spec.py", line 12, in <module>
    from fsspec.asyn import (
ImportError: cannot import name 'fsspec_loop' from 'fsspec.asyn' (/home/maximilian/.conda/envs/test-sshfs/lib/python3.10/site-packages/fsspec/asyn.py)
```

downgrading fsspec to 2022.11.0 resolves the issue for me.
I'm opening this, to suggest adding a constraint fsspec <= 2022.11.0 to the meta.yaml

### Installed packages

```shell
# packages in environment at /home/maximilian/.conda/envs/test-sshfs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge  
_openmp_mutex             4.5                       2_gnu  
asyncssh                  2.13.0             pyhd8ed1ab_0  
bzip2                     1.0.8                h7f98852_4  
ca-certificates           2022.12.7            ha878542_0  
cffi                      1.15.1          py310h255011f_3  
cryptography              39.0.0          py310h34c0648_0  
decorator                 5.1.1              pyhd8ed1ab_0  
fsspec                    2023.1.0           pyhd8ed1ab_0  
keyutils                  1.6.1                h166bdaf_0  
krb5                      1.20.1               h81ceb04_0  
ld_impl_linux-64          2.39                 hcc3a1bd_1  
libedit                   3.1.20191231         he28a2e2_2  
libffi                    3.4.2                h7f98852_5  
libgcc-ng                 12.2.0              h65d4601_19  
libgomp                   12.2.0              h65d4601_19  
libnsl                    2.0.0                h7f98852_0  
libsqlite                 3.40.0               h753d276_0  
libstdcxx-ng              12.2.0              h46fd767_19  
libuuid                   2.32.1            h7f98852_1000  
libzlib                   1.2.13               h166bdaf_4  
ncurses                   6.3                  h27087fc_1  
openssl                   3.0.7                h0b41bf4_1  
pip                       22.3.1             pyhd8ed1ab_0  
pycparser                 2.21               pyhd8ed1ab_0  
pyopenssl                 23.0.0             pyhd8ed1ab_0  
python                    3.10.8          h4a9ceb5_0_cpython  
python-gssapi             1.8.2           py310hd1ceca7_2  
python_abi                3.10                    3_cp310  
readline                  8.1.2                h0f457ee_0  
setuptools                66.0.0             pyhd8ed1ab_0  
sshfs                     2022.6.0           pyhd8ed1ab_1  
tk                        8.6.12               h27826a3_0  
typing_extensions         4.4.0              pyha770c72_0  
tzdata                    2022g                h191b570_0  
wheel                     0.38.4             pyhd8ed1ab_0  
xz                        5.2.6                h166bdaf_0
```

### Environment info

```shell
active environment : test-sshfs
    active env location : /home/maximilian/.conda/envs/test-sshfs
            shell level : 7
       user config file : /home/maximilian/.condarc
 populated config files : /opt/miniconda3/.condarc
                          /home/maximilian/.condarc
          conda version : 22.11.1
    conda-build version : 3.23.3
         python version : 3.10.8.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/miniconda3  (read only)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : http://evalaendata0.dnb.de/aen-forge/linux-64
                          http://evalaendata0.dnb.de/aen-forge/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/maximilian/.conda/pkgs
       envs directories : /home/maximilian/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.2 CPython/3.10.8 Linux/5.15.0-56-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 3004:100
             netrc file : None
           offline mode : False
```

**Comment by pmrowla** [comment]
The solution here should be updating to sshfs 2023.1.0 or later, which includes the fix to support the newer fsspec releases. I've removed the constraint in the sshfs 2023.4.1 conda package release as we should not be restricting fsspec versions

If for some reason you need an older sshfs release you can explicitly install
```
conda install -c conda-forge "fsspec<=2022.11.0"
```

**Comment by mfakaehler** [comment]
I agree, if the broken dependency to fsspec is now repaired in a newer release of sshfs, then there is no need for this constraint any more. Thank you
